#
# file    : Makefile.tmpl
#
# Desc    :
# Created : 2017. 12. 10
# Author  : jeho park<linuxpark@gmail.com>

PROG                = gy86
### check 1. uart device file.
ISP_DEV_NAME        = /dev/tty.usbserial-DN018JNZ
### check 2. isp device.
ISP_PROG_TYPE       = stk500
OBJS                = i2c.o uart.o ms5611.o main.o
### check 3. target mcu.
MCU_TARGET          = atmega128
OPTIMIZE            = -O1
OPTIMIZE           += -D__OPTIMIZE__
CC                  = /opt/local/bin/avr-gcc 
OBJCOPY             = /opt/local/bin/avr-objcopy
OBJDUMP             = /opt/local/bin/avr-objdump 
LOADER              = /opt/local/bin/avrdude
INC                 = -I.
# CFLAGS
########
CFLAGS             = -g -Wall -gdwarf-2
CFLAGS             += -std=gnu99 -Wl,-u,vfprintf
CFLAGS             += -Wshift-count-overflow
CFLAGS             += $(INC)
CFLAGS             += $(OPTIMIZE)
CFLAGS             += -mmcu=$(MCU_TARGET)
CFLAGS             += -DDEBUG
### check 4. mcu clock hz.
CFLAGS             += -DF_CPU=16000000UL
### check 5. i2c clock hz.
CFLAGS             += -DSCL_CLOCK=100000L
########
LDFLAGS             = -Wl,-Map,$(PROG).map
LIBS                = -lm -lprintf_flt
EXTRA_CLEAN_FILES   = *.hex *.bin *.srec
# $brew install ctags
CTAGS               = /usr/local/Cellar/ctags/5.8_1/bin/ctags
