#
# file    : Makefile.tmpl
#
# Desc    :
# Created : 2017. 12. 10
# Author  : jeho park<linuxpark@gmail.com>

MCU_TARGET          = atmega128
# DEV_OS: MAC, LINUX
DEV_OS              = LINUX
PROG                = gy86

#CFLAGS             += -DMS5611_TEST
#CFLAGS             += -DHMC5883_TEST
#CFLAGS             += -DQMC5883_TEST
CFLAGS             += -DMPU6050_TEST

#ISP_DEV_NAME        = /dev/tty.usbserial-DN018JNZ
ISP_DEV_NAME        = /dev/ttyUSB1

ISP_PROG_TYPE       = stk500

### MAC OSX
ifeq ($(DEV_OS),MAC)
CROSS_COMPILER	    = /opt/local/bin
CTAGS               = /usr/local/Cellar/ctags/5.8_1/bin/ctags
else ifeq ($(DEV_OS),LINUX)
### LINUX
CROSS_COMPILER	    = /usr/bin
CTAGS               = /usr/bin/ctags
endif

CC                  = ${CROSS_COMPILER}/avr-gcc 
OBJCOPY             = ${CROSS_COMPILER}/avr-objcopy
OBJDUMP             = ${CROSS_COMPILER}/avr-objdump
LOADER              = ${CROSS_COMPILER}/avrdude
INC                 = -I.
# CFLAGS CFLAGS     = -g -Wall -gdwarf-2
CFLAGS             += -std=gnu99 -Wl,-u,vfprintf -Wall
CFLAGS             += $(INC)
CFLAGS             += -O1 -D__OPTIMIZE__ 
CFLAGS             += -mmcu=$(MCU_TARGET)
CFLAGS             += -DDEBUG
LDFLAGS             = -Wl,-Map,$(PROG).map
LIBS                = -lm -lprintf_flt
EXTRA_CLEAN_FILES   = *.hex *.bin *.srec
# $brew install ctags
#CTAGS               = /usr/local/Cellar/ctags/5.8_1/bin/ctags
CTAGS               = /usr/bin/ctags
OBJS                = i2c.o uart.o main.o ms5611.o hmc5883l.o qmc5883.o mpu6050.o
